var DataFrame;
DataFrame.prototype.castAll;
DataFrame.prototype.chain;
DataFrame.prototype.dropMissingValues;
DataFrame.prototype.filter;
DataFrame.prototype.find;
DataFrame.prototype.fromCSV;
DataFrame.prototype.get;
DataFrame.prototype.reduce;
DataFrame.prototype.renameAll;
DataFrame.prototype.set;
DataFrame.prototype.show;
DataFrame.prototype.sortBy;
DataFrame.prototype.stat;
DataFrame.prototype.stat.mean;
DataFrame.prototype.toCollection;
DataFrame.prototype.transpose;
DataFrame.prototype.unique;
